apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Application Release with manifest
on:
  workflow_dispatch:
    inputs:
      manifest:
        type: string
        required: true
jobs:
  pre-prod:
    steps:
      - name: Deploy App3-Frontend to Preprod
        kind: deploy
        if: ${{ fromJSON(inputs.manifest)['App3-Frontend']['App3-Frontend'].deploy }}
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          version: ${{ fromJSON(inputs.manifest)['App3-Frontend']['App3-Frontend'].version }}
          url: ${{ fromJSON(inputs.manifest)['App3-Frontend']['App3-Frontend'].url }}
          digest: ${{ fromJSON(inputs.manifest)['App3-Frontend']['App3-Frontend'].digest }}
          target-environment: pre-prod
          name: App3-Frontend

      - name: Deploy App3-Backend to Preprod
        kind: deploy
        if: ${{ fromJSON(inputs.manifest)['App3-Backend']['App3-Backend'].deploy }}
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          version: ${{ fromJSON(inputs.manifest)['App3-Backend']['App3-Backend'].version }}
          url: ${{ fromJSON(inputs.manifest)['App3-Backend']['App3-Backend'].url }}
          digest: ${{ fromJSON(inputs.manifest)['App3-Backend']['App3-Backend'].digest }}
          target-environment: pre-prod
          name: App3-Backend

      - name: Deploy App3-APIs to Preprod
        kind: deploy
        if: ${{ fromJSON(inputs.manifest)['App3-APIs']['App3-APIs'].deploy }}
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          version: ${{ fromJSON(inputs.manifest)['App3-APIs']['App3-APIs'].version }}
          url: ${{ fromJSON(inputs.manifest)['App3-APIs']['App3-APIs'].url }}
          digest: ${{ fromJSON(inputs.manifest)['App3-APIs']['App3-APIs'].digest }}
          target-environment: pre-prod
          name: App3-APIs
  prod:
    needs: pre-prod
    steps:
      - name: Deploy App3-Frontend to Prod
        kind: deploy
        if: ${{ fromJSON(inputs.manifest)['App3-Frontend']['App3-Frontend'].deploy }}
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          version: ${{ fromJSON(inputs.manifest)['App3-Frontend']['App3-Frontend'].version }}
          url: ${{ fromJSON(inputs.manifest)['App3-Frontend']['App3-Frontend'].url }}
          digest: ${{ fromJSON(inputs.manifest)['App3-Frontend']['App3-Frontend'].digest }}
          target-environment: prod
          name: App3-Frontend

      - name: Deploy App3-Backend to Prod
        kind: deploy
        if: ${{ fromJSON(inputs.manifest)['App3-Backend']['App3-Backend'].deploy }}
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          version: ${{ fromJSON(inputs.manifest)['App3-Backend']['App3-Backend'].version }}
          url: ${{ fromJSON(inputs.manifest)['App3-Backend']['App3-Backend'].url }}
          digest: ${{ fromJSON(inputs.manifest)['App3-Backend']['App3-Backend'].digest }}
          target-environment: prod
          name: App3-Backend

      - name: Deploy App3-APIs to Prod
        kind: deploy
        if: ${{ fromJSON(inputs.manifest)['App3-APIs']['App3-APIs'].deploy }}
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          version: ${{ fromJSON(inputs.manifest)['App3-APIs']['App3-APIs'].version }}
          url: ${{ fromJSON(inputs.manifest)['App3-APIs']['App3-APIs'].url }}
          digest: ${{ fromJSON(inputs.manifest)['App3-APIs']['App3-APIs'].digest }}
          target-environment: prod
          name: App3-APIs
